# X Axis
[modules.xmirror]
docs = """
Mirrors children around the X axis
"""
dimensions = 0
operator = true
code = """
mirror([1, 0, 0]) children();
"""

# Y Axis
[modules.ymirror]
docs = """
Mirrors children around the Y axis
"""
dimensions = 0
operator = true
code = """
mirror([0, 1, 0]) children();
"""

# Z Axis
[modules.zmirror]
docs = """
Mirrors children around the Z axis
"""
dimensions = 0
operator = true
code = """
mirror([0, 0, 1]) children();
"""

