# X Axis
[modules.rotate_x]
docs = """
Rotates children around the X axis by the given number of degrees.
"""
dimensions = 0
operator = true
code = """
rotate([a, 0, 0]) children();
"""

[modules.rotate_x.parameters.angle]
name = "a"
type = "angle"
default = 0.0

[modules.rotate_x_around]
docs = """
Rotates children around the X axis by the given number of degrees at a centerpoint.
"""
dimensions = 0
operator = true
code = """
if (!is_undef(cp)) { translate(cp) rotate([a, 0, 0]) translate(-cp) children(); }
else { rotate([a, 0, 0]) children(); }
"""

[modules.rotate_x_around.constructors._default]
arguments = ["angle"]

[modules.rotate_x_around.parameters.angle]
name = "a"
type = "angle"
default = 0.0

[modules.rotate_x_around.parameters.centerpoint]
name = "cp"
type = "length3"
alt = ["length"]

# Y Axis
[modules.rotate_y]
docs = """
Rotates children around the Y axis by the given number of degrees.
"""
dimensions = 0
operator = true
code = """
rotate([0, a, 0]) children();
"""

[modules.rotate_y.parameters.angle]
name = "a"
type = "angle"
default = 0.0

[modules.rotate_y_around]
docs = """
Rotates children around the Y axis by the given number of degrees at a centerpoint.
"""
dimensions = 0
operator = true
code = """
if (!is_undef(cp)) { translate(cp) rotate([0, a, 0]) translate(-cp) children(); }
else { rotate([0, a, 0]) children(); }
"""

[modules.rotate_y_around.constructors._default]
arguments = ["angle"]

[modules.rotate_y_around.parameters.angle]
name = "a"
type = "angle"
default = 0.0

[modules.rotate_y_around.parameters.centerpoint]
name = "cp"
type = "length3"
alt = ["length"]

# Z Axis
[modules.rotate_z]
docs = """
Rotates children around the Z axis by the given number of degrees.
"""
dimensions = 0
operator = true
code = """
rotate([0, 0, a]) children();
"""

[modules.rotate_z.parameters.angle]
name = "a"
type = "angle"
default = 0.0

[modules.rotate_z_around]
docs = """
Rotates children around the Z axis by the given number of degrees at a centerpoint.
"""
dimensions = 0
operator = true
code = """
if (!is_undef(cp)) { translate(cp) rotate([0, 0, a]) translate(-cp) children(); }
else { rotate([0, 0, a]) children(); }
"""

[modules.rotate_z_around.constructors._default]
arguments = ["angle"]

[modules.rotate_z_around.parameters.angle]
name = "a"
type = "angle"
default = 0.0

[modules.rotate_z_around.parameters.centerpoint]
name = "cp"
type = "length3"
alt = ["length"]
