# $fa
[modules.fragment_angle]
docs = """
The minimum angle for a fragment.

Even a huge circle does not have more fragments than 360 divided by this number. The default value is 12 (i.e. 30 fragments for a full circle). The minimum allowed value is 0.01. Attempting to set a lower value causes a warning.
"""
dimensions = 0
operator = true
code = """
$fa = ($preview && !is_undef(p)) ? p : v; children();
"""

[modules.fragment_angle.constructors._default]
arguments = ["angle"]

[modules.fragment_angle.parameters.angle]
name = "v"
type = "angle"
default = 12.0

[modules.fragment_angle.parameters.preview]
name = "p"
type = "angle"

# $fs
[modules.fragment_size]
docs = """
The minimum size of a fragment.

The default value is 2 so very small circles have a smaller number of fragments than specified using `fragment_angle`. The minimum allowed value is 0.01. Attempting to set a lower value causes a warning.
"""
dimensions = 0
operator = true
code = """
$fs = ($preview && !is_undef(p)) ? p : v; children();
"""

[modules.fragment_size.constructors._default]
arguments = ["size"]

[modules.fragment_size.parameters.size]
name = "v"
type = "length"
default = 2.0

[modules.fragment_size.parameters.preview]
name = "p"
type = "length"

# $fn
[modules.fragment_count]
docs = """
The number of fragments and usually has the default value of 0.

When this variable has a value greater than zero, the `fragment_angle` and `fragment_size` are ignored, and a full circle is rendered using this number of fragments.
"""
dimensions = 0
operator = true
code = """
$fn = ($preview && !is_undef(p)) ? p : v; children();
"""

[modules.fragment_count.constructors._default]
arguments = ["count"]

[modules.fragment_count.parameters.count]
name = "v"
type = "scalar"
default = 0.0

[modules.fragment_count.parameters.preview]
name = "p"
type = "length"
