[modules.scale_x]
docs = """
Scales children by the given factor on the X axis.
"""
dimensions = 0
operator = true
code = """
scale([x, 1, 1]) children();
"""

[modules.scale_x.parameters.x]
type = "scalar"

[modules.scale_y]
docs = """
Scales children by the given factor on the Y axis.
"""
dimensions = 0
operator = true
code = """
scale([1, y, 1]) children();
"""

[modules.scale_y.parameters.y]
type = "scalar"

[modules.scale_z]
docs = """
Scales children by the given factor on the Z axis.
"""
dimensions = 0
operator = true
code = """
scale([1, 1, z]) children();
"""

[modules.scale_z.parameters.z]
type = "scalar"
