[modules.linear_extrude]
docs = """
Linear Extrusion is an operation that takes a 2D object as input and generates a 3D object as a result.

Extrusion follows the V vector which defaults to the Z axis, for specifying a custom value a version > 2021.01 is needed.

In OpenSCAD Extrusion is always performed on the projection (shadow) of the 2d object xy plane; so if you rotate or apply other transformations to the 2d object before extrusion, its shadow shape is what is extruded.

Although the extrusion is linear along the V vector, a twist parameter is available that causes the object to be rotated around the V vector as it is extruding upward. This can be used to rotate the object at its center, as if it is a spiral pillar, or produce a helical extrusion around the V vector, like a pig's tail.

A scale parameter is also included so that the object can be expanded or contracted over the extent of the extrusion, allowing extrusions to be flared inward or outward.
"""
dimensions = 3
dimensions_in = 2
operator = true

[modules.linear_extrude.constructors._default]
arguments = ["height"]

# TODO add the rest of the parameters

[modules.linear_extrude.parameters.height]
type = "length"

[modules.linear_extrude.parameters.vector]
name = "v"
type = "length3"
alt = ["length"]

[modules.linear_extrude.parameters.center]
type = "bool"
default = true

[modules.linear_extrude.parameters.convexity]
type = "scalar"
default = 10.0

[modules.linear_extrude.parameters.twist]
type = "angle"
default = 0.0

[modules.rotate_extrude]
docs = """
Rotational extrusion spins a 2D shape around the Z-axis to form a solid which has rotational symmetry. One way to think of this operation is to imagine a Potter's wheel placed on the X-Y plane with its axis of rotation pointing up towards +Z. Then place the to-be-made object on this virtual Potter's wheel (possibly extending down below the X-Y plane towards -Z). The to-be-made object is the cross-section of the object on the X-Y plane (keeping only the right half, X >= 0). That is the 2D shape that will be fed to rotate_extrude() as the child in order to generate this solid. Note that the object started on the X-Y plane but is tilted up (rotated +90 degrees about the X-axis) to extrude.

Since a 2D shape is rendered by OpenSCAD on the X-Y plane, an alternative way to think of this operation is as follows: spins a 2D shape around the Y-axis to form a solid. The resultant solid is placed so that its axis of rotation lies along the Z-axis.

Just like the [`linear_extrude`], the extrusion is always performed on the projection of the 2D polygon to the XY plane. Transformations like rotate, translate, etc. applied to the 2D polygon before extrusion modify the projection of the 2D polygon to the XY plane and therefore also modify the appearance of the final 3D object.

* A translation in Z of the 2D polygon has no effect on the result (as also the projection is not affected).
* A translation in X increases the diameter of the final object.
* A translation in Y results in a shift of the final object in Z direction.
* A rotation about the X or Y axis distorts the cross section of the final object, as also the projection to the XY plane is distorted.

Don't get confused, as OpenSCAD renders 2D polygons with a certain height in the Z direction, so the 2D object (with its height) appears to have a bigger projection to the XY plane. But for the projection to the XY plane and also for the later extrusion only the base polygon without height is used.

It can not be used to produce a helix or screw threads. (These things can be done with [`linear_extrude`] using the twist parameter.)

The 2D shape must lie completely on either the right (recommended) or the left side of the Y-axis. More precisely speaking, every vertex of the shape must have either x >= 0 or x <= 0. If the shape spans the X axis a warning appears in the console windows and the rotate_extrude() is ignored. If the 2D shape touches the Y axis, i.e. at x=0, it must be a line that touches, not a point, as a point results in a zero thickness 3D object, which is invalid and results in a CGAL error. For OpenSCAD versions prior to 2016.xxxx, if the shape is in the negative axis the resulting faces are oriented inside-out, which may cause undesired effects.
"""
dimensions = 3
dimensions_in = 2
operator = true

[modules.rotate_extrude.constructors._default]
arguments = []

[modules.rotate_extrude.parameters.angle]
docs = """
Defaults to 360. Specifies the number of degrees to sweep, starting at the positive X axis. The direction of the sweep follows the Right Hand Rule, hence a negative angle sweeps clockwise.
"""
type = "angle"
default = 360.0

[modules.rotate_extrude.parameters.convexity]
docs = """
If the extrusion fails for a non-trival 2D shape, try setting the convexity parameter (the default is not 10, but 10 is a "good" value to try). See explanation further down.
"""
type = "scalar"
default = 2.0

[modules.rotate_extrude.parameters.fragment_angle]
name = "$fa"
docs = """
Fragment angle in degrees
"""
type = "angle"
default = 12.0

[modules.rotate_extrude.parameters.fragment_size]
name = "$fs"
docs = """
Fragment size in mm
"""
type = "length"
default = 2.0

[modules.rotate_extrude.parameters.fragment_resolution]
name = "$fn"
docs = """
Fragment resolution
"""
type = "fragment_resolution"
default = 0.0
